RegisterCommand("help", function()
    msg("Server's Discord: discord.gg/asdf")
    msg("Server's Website: https://KarmaCrewCommunity.com")
    msg("/help-rp - RolePlay Help")
    msg("/help-police - Police Help")
    msg("/help-race - Race Help")
end, false)


RegisterCommand ("help-race", function ()
    msg("/race start amount [delay] - Start a race for money using waypoint or recorded checkpoints")
    msg("Optional argument for delay before race starts (default 30s)")
    msg("/race cancel - Cancel a created race before it starts and refund money")
    msg("/race leave - Withdraw from the active race (no refunds)")
    msg("/race record - Record checkpoints using map")
    msg("Set waypoints on the map to create checkpoints (snaps to nearest vehicle path node)")
    msg("Double click existing checkpoints to remove")
    msg("/race clear - Clear recorded checkpoints")
    msg("/race save name - Save recorded checkpoints with name")
    msg("/race load name - Load recorded checkpoints with name")
    msg("/race delete name - Delete recorded checkpoints with name")
    msg("/race list - List saved checkpoints by name")
end, false)

RegisterCommand ("help-police", function ()
    msg("/id <fname> <sname> <dob*> - Shows id with desired name")
    msg("/p - Displays a panic message in chat")
    msg("/4 - Sends a 10-4 message in radio chat")
    msg("/20 (could also be activated via a keybind. Check the configs for more info) - Displays your location in chat")
    msg("/8 - Shows you 10-8")
    msg("/8f - Shows you 10-8, on foot")
    msg("/7, 7f, 7g, 7i - Shows you 10-7, unavailable")
    msg("/6, 6m - Shows you 10-6, unavailable unless urgent")
    msg("/80 - Shows you in a pursuit")
    msg("/code4 - Sends a Code 4 message in radio chat")
    msg("/32 <1/2/3> - Requests backup, Code 1, 2 or 3")
    msg("/47 <1/2/3> - RShows you responding, Code 1, 2 or 3")
    msg("/23 - Shows you 10-23, on scene")
    msg("/11 <color | veh info> - Shows you on a traffic stop")
    msg("/28 <numplate | veh info> - Requests a 10-28 (Plate Check)")
    msg("/29 <fname | sname> - Requests a 10-28 (Plate Check)")

    msg("Radar Gun")
    msg("Press Y to open the menu thing")
    msg("Press E to take measurement")
end, false)


RegisterCommand ("help-rp", function ()
    msg("// - Out of Character chat. (OOC)")
    msg("/me - Player actions")
    msg("/it - Object actions")
    msg("/r (/radio) - Radio chat")
    msg("/dispatch - Dispatcher chat")
    msg("/911 - Generates a random caller ID and sends a 911 message")
    msg("/rpname <fname_surname> <text> - Displays a chat message using the set name")
    msg("/roll - Rolls a dice")
end, false)

RegisterCommand ("help-server", function ()
    msg("/register - ")
    msg("/char - ")
    msg("/chardel - ")
end, false)

RegisterCommand ("help-money", function ()
    msg("/showcash - Cash in Wallet")
    msg("/showbank - Bank Balance")
    msg("/showdirty - Dirty Money")
    msg("/showjob - Job Title")
    msg("/showsociety - Society Money")
    msg("/showall - Show All")
end, false)


function msg(text)
    TriggerEvent("chatMessage", "[Server]", {255,0,0}, text)
end


